service: gp-pytorch-lambda-layer

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-south-1
  timeout: 60

layers:
  gp-pytorch-torchvision-pillow-layer:
    package:
      artifact: torchLayerPackages.zip
    description: This layer contains pytorch 1.5.1, torch vision 0.6.1, Pillow and its dependencies
    compatibleRuntimes: 
      - python3.8
    licenseInfo: GPLv3 
    allowedAccounts: 
      - '*'