service: gp-german-to-eng-service

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: ap-south-1
  timeout: 60
  environment:
    S3_BUCKET: gauravp-s11-german-english-translation-models
    SRC_TEXT_FIELD: SRC_fields.pkl
    TRG_TEXT_FIELD: TRG_fields.pkl
    MODEL_PATH: translation_model.pt
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:getObject
      Resource: arn:aws:s3:::gauravp-s11-german-english-translation-models/*    



functions:
  translate:
    handler: handler.hello
    memorySize: 3008
    timeout: 60
    events:
      - http:
          path: translate
          method: post
          cors: true
    layers:
      - arn:aws:lambda:ap-south-1:503625344141:layer:gp-torchtext-spacy-pytorch-layer:1