service: human-pose-estimation-service
provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-south-1
  timeout: 60
  environment:
    S3_BUCKET: gauravp-human-pose-estimation-models
    MODEL_PATH: pose_resnet_50_256x256.pth.tar
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:getObject
      Resource: arn:aws:s3:::gauravp-human-pose-estimation-models/*

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true
    strip: false
    noDeploy:
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - setuptools
      - six
      - tensorboard
    useStaticCache: true
    useDownloadCache: true
    cacheLocation: "./cache"

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**
    - cache/**
    - test/**
    - __pycache__/**
    - .pytest_cache/**
    - model/**

functions:
  estimate_pose:
    handler: handler.estimate_pose
    memorySize: 3008
    timeout: 60
    events:
      - http:
          path: estimate_pose
          method: post
          cors: true

plugins:
  - serverless-python-requirements
