service: style-transfer-service-with-layer

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-south-1
  timeout: 60
  environment:
    S3_BUCKET: gauravp-neural-style-transfer-models
    MODEL_PATH: vgg19_model.pth
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:getObject
      Resource: arn:aws:s3:::gauravp-neural-style-transfer-models/*


functions:
  transfer_style:
    handler: handler.transfer_style
    memorySize: 3008
    timeout: 60
    events:
      - http:
          path: transfer_style
          method: post
          cors: true
    layers:
      - arn:aws:lambda:ap-south-1:503625344141:layer:gp-pytorch-torchvision-pillow-layer:1
